### ISSUE TITLE
groupBy example does not work with spark 2.1

### ISSUE THREAD

**Issue by thunterdb** [databricks/tensorframes#78]
The example in the wiki triggers the following error:

```
AttributeError: 'GroupedData' object has no attribute '_jdf'

df3 = tfs.aggregate([x, count], gb)

tensorframes/core.py in aggregate(fetches, grouped_data)
    294     fetches = _check_fetches(fetches)
    295     graph = _get_graph(fetches)
--> 296     builder = _java_api().aggregate_blocks(grouped_data._jdf)
```

**Comment by thunterdb** [comment]
This causes the K-Means example to fail as well.

**Comment by thunterdb** [comment]
This is an issue with spark 2.1
